apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: angular-acronym
        tier: frontend
    spec:
      containers:
      - name: acronymapp-angular
        image: suizhidaidev/angular-acronym:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
